<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-10-15">

<title>Sarah Silver test - Untitled</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/personal_logo.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sarah Silver test</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html" rel="" target="">
 <span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html" rel="" target="">
 <span class="menu-text">Resume</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lhba-house-pricing-model" id="toc-lhba-house-pricing-model" class="nav-link active" data-scroll-target="#lhba-house-pricing-model">LHBA House Pricing Model</a>
  <ul class="collapse">
  <li><a href="#to-the-best-of-your-ability-strive-develop-a-clear-description-of-the-lhbas-big-picture-business-problem.-then-define-some-more-clearly-defined-sub-problems-that-would-be-more-specific-questions-or-problems-whose-solution-would-be-inline-with-solving-lhbas-problem." id="toc-to-the-best-of-your-ability-strive-develop-a-clear-description-of-the-lhbas-big-picture-business-problem.-then-define-some-more-clearly-defined-sub-problems-that-would-be-more-specific-questions-or-problems-whose-solution-would-be-inline-with-solving-lhbas-problem." class="nav-link" data-scroll-target="#to-the-best-of-your-ability-strive-develop-a-clear-description-of-the-lhbas-big-picture-business-problem.-then-define-some-more-clearly-defined-sub-problems-that-would-be-more-specific-questions-or-problems-whose-solution-would-be-inline-with-solving-lhbas-problem.">To the best of your ability, strive develop a clear description of the LHBA’s big-picture business problem. Then define some more clearly defined sub-problems that would be more specific questions or problems whose solution would be inline with solving LHBA’s problem.</a></li>
  <li><a href="#write-3-high-quality-questions-you-would-want-to-ask-lhba-stakeholders-to-follow-up-and-get-more-information-or-insight-into-their-business." id="toc-write-3-high-quality-questions-you-would-want-to-ask-lhba-stakeholders-to-follow-up-and-get-more-information-or-insight-into-their-business." class="nav-link" data-scroll-target="#write-3-high-quality-questions-you-would-want-to-ask-lhba-stakeholders-to-follow-up-and-get-more-information-or-insight-into-their-business.">Write 3 high quality questions you would want to ask LHBA stakeholders to follow up and get more information or insight into their business.</a></li>
  <li><a href="#translate-lhbas-framed-business-problem-into-an-analytics-problem-i.e.-numbersmeasures-to-calculate-things-to-predict-how-to-visualize-or-present-those-things-to-affect-a-decision-etc..-make-sure-to-connect-your-business-analytic-problems-to-decisions-that-need-to-be-made-and-ask-yourself-if-the-data-science-will-improve-the-decision-and-what-the-value-of-the-improved-decision-making-could-be." id="toc-translate-lhbas-framed-business-problem-into-an-analytics-problem-i.e.-numbersmeasures-to-calculate-things-to-predict-how-to-visualize-or-present-those-things-to-affect-a-decision-etc..-make-sure-to-connect-your-business-analytic-problems-to-decisions-that-need-to-be-made-and-ask-yourself-if-the-data-science-will-improve-the-decision-and-what-the-value-of-the-improved-decision-making-could-be." class="nav-link" data-scroll-target="#translate-lhbas-framed-business-problem-into-an-analytics-problem-i.e.-numbersmeasures-to-calculate-things-to-predict-how-to-visualize-or-present-those-things-to-affect-a-decision-etc..-make-sure-to-connect-your-business-analytic-problems-to-decisions-that-need-to-be-made-and-ask-yourself-if-the-data-science-will-improve-the-decision-and-what-the-value-of-the-improved-decision-making-could-be.">Translate LHBA’s framed business problem into an analytics problem (i.e., numbers/measures to calculate, things to predict, how to visualize or present those things to affect a decision, etc.). Make sure to connect your business / analytic problems to decisions that need to be made and ask yourself if the “data science” will improve the decision and what the value of the improved decision making could be.</a></li>
  <li><a href="#write-a-couple-of-paragraphs-describing-how-crisp-dm-would-apply-to-the-process-of-providing-lhba-with-a-solution." id="toc-write-a-couple-of-paragraphs-describing-how-crisp-dm-would-apply-to-the-process-of-providing-lhba-with-a-solution." class="nav-link" data-scroll-target="#write-a-couple-of-paragraphs-describing-how-crisp-dm-would-apply-to-the-process-of-providing-lhba-with-a-solution.">Write a couple of paragraphs describing how CRISP-DM would apply to the process of providing LHBA with a solution.</a></li>
  <li><a href="#prepare-the-data-as-necessary-and-train-a-model-to-predict-home-selling-prices-making-sure-to-evaluate-its-performance-on-the-test-data-and-interpret-the-error-and-its-meaning-for-lhba-operations." id="toc-prepare-the-data-as-necessary-and-train-a-model-to-predict-home-selling-prices-making-sure-to-evaluate-its-performance-on-the-test-data-and-interpret-the-error-and-its-meaning-for-lhba-operations." class="nav-link" data-scroll-target="#prepare-the-data-as-necessary-and-train-a-model-to-predict-home-selling-prices-making-sure-to-evaluate-its-performance-on-the-test-data-and-interpret-the-error-and-its-meaning-for-lhba-operations.">Prepare the data as necessary and train a model to predict home selling prices, making sure to evaluate its performance on the test data and interpret the error and its meaning for LHBA operations.</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Untitled</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 15, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice

Attaching package: 'caret'

The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(FNN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>pre <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"PreCrisisCV.csv"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"PostCrisisCV.csv"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>market <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"OnMarketTest.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="lhba-house-pricing-model" class="level1">
<h1>LHBA House Pricing Model</h1>
<section id="to-the-best-of-your-ability-strive-develop-a-clear-description-of-the-lhbas-big-picture-business-problem.-then-define-some-more-clearly-defined-sub-problems-that-would-be-more-specific-questions-or-problems-whose-solution-would-be-inline-with-solving-lhbas-problem." class="level3">
<h3 class="anchored" data-anchor-id="to-the-best-of-your-ability-strive-develop-a-clear-description-of-the-lhbas-big-picture-business-problem.-then-define-some-more-clearly-defined-sub-problems-that-would-be-more-specific-questions-or-problems-whose-solution-would-be-inline-with-solving-lhbas-problem.">To the best of your ability, strive develop a clear description of the LHBA’s big-picture business problem. Then define some more clearly defined sub-problems that would be more specific questions or problems whose solution would be inline with solving LHBA’s problem.</h3>
<p>The Local Home Builder’s Association’s business relies on accurate house pricing prediction. Historically, they have used county-assessed home values, which were typically similar to the final sale price of each home. However, due to the 2008 financial crisis, market forces have caused house prices to differ significantly from their assessed values. Thus, a new pricing model which takes into account current house pricing trends is necessary for LHBA, as their revenue model relies on the purchase, sale, lending, and construction of homes.</p>
<p>Some sub-problems/questions might include:</p>
<ul>
<li><p>What is the difference in housing pricing patterns before and after the market crash? How does this affect the pricing of the products LHBA offers? What are other companies that offer similar products to LHBA doing about this issue?</p></li>
<li><p>What is the current pricing model dependent on and why is it not in line with market realities?</p></li>
<li><p>What predictive factors/data do we have access to for building our model?</p></li>
</ul>
</section>
<section id="write-3-high-quality-questions-you-would-want-to-ask-lhba-stakeholders-to-follow-up-and-get-more-information-or-insight-into-their-business." class="level3">
<h3 class="anchored" data-anchor-id="write-3-high-quality-questions-you-would-want-to-ask-lhba-stakeholders-to-follow-up-and-get-more-information-or-insight-into-their-business.">Write 3 high quality questions you would want to ask LHBA stakeholders to follow up and get more information or insight into their business.</h3>
<ul>
<li><p>What are some instances in which the county-assessed valuation has significantly differed from the sale price of the house? How did this affect LHBA’s revenue or decision-making process?</p></li>
<li><p>How will the new pricing model be incorporated into LHBA’s day-to-day operations? Who will be accessing the predictions and what will they use them for? Is interprability or accuracy a greater concern?</p></li>
<li><p>How has the financial crisis affected LHBA in ways other than the obsolete pricing model? Are there any specific business issues LHBA is facing that we should take into account while building the new model?</p></li>
</ul>
</section>
<section id="translate-lhbas-framed-business-problem-into-an-analytics-problem-i.e.-numbersmeasures-to-calculate-things-to-predict-how-to-visualize-or-present-those-things-to-affect-a-decision-etc..-make-sure-to-connect-your-business-analytic-problems-to-decisions-that-need-to-be-made-and-ask-yourself-if-the-data-science-will-improve-the-decision-and-what-the-value-of-the-improved-decision-making-could-be." class="level3">
<h3 class="anchored" data-anchor-id="translate-lhbas-framed-business-problem-into-an-analytics-problem-i.e.-numbersmeasures-to-calculate-things-to-predict-how-to-visualize-or-present-those-things-to-affect-a-decision-etc..-make-sure-to-connect-your-business-analytic-problems-to-decisions-that-need-to-be-made-and-ask-yourself-if-the-data-science-will-improve-the-decision-and-what-the-value-of-the-improved-decision-making-could-be.">Translate LHBA’s framed business problem into an analytics problem (i.e., numbers/measures to calculate, things to predict, how to visualize or present those things to affect a decision, etc.). Make sure to connect your business / analytic problems to decisions that need to be made and ask yourself if the “data science” will improve the decision and what the value of the improved decision making could be.</h3>
<p>Our goal is to build a regression model to predict home prices in order for LHBA to make informed, data-driven business decisions that will allow the business and their clients to make the most out of their products and services. We will train our model using relevant factors including lot size, square footage, number of beds/baths, age of house, and condition, among others. By performing cross-validation, we will be able to test our model and assess its accuracy.</p>
</section>
<section id="write-a-couple-of-paragraphs-describing-how-crisp-dm-would-apply-to-the-process-of-providing-lhba-with-a-solution." class="level3">
<h3 class="anchored" data-anchor-id="write-a-couple-of-paragraphs-describing-how-crisp-dm-would-apply-to-the-process-of-providing-lhba-with-a-solution.">Write a couple of paragraphs describing how CRISP-DM would apply to the process of providing LHBA with a solution.</h3>
<p>The first step to solving this issue using the CRISP-DM approach is getting an understanding of the business problem at hand. This would involve communicating with LHBA about their experiences surrounding the issue and figuring out what the business needs from you as a data scientist.</p>
<p>Next, we need to understand the data we have, and the data we need. In our context, we have pre- and post-crisis housing price datasets, as well as a dataset with current house listings in the area which haven’t sold yet. Our goal in this step is to understand what each column is and what the values in these columns mean. We also need to assess the quality of our data. Do we have missing values? Are there values that don’t make sense in context? This also incorporates the next step in CRISP-DM, data preparation. Here, we use the understanding we’ve gained about our datasets and clean them up accordingly. This includes dealing with missing values through methods like imputation, or dropping columns we deem unnecessary. We also normalize our numerical variables to get values on a similar scale.</p>
</section>
<section id="prepare-the-data-as-necessary-and-train-a-model-to-predict-home-selling-prices-making-sure-to-evaluate-its-performance-on-the-test-data-and-interpret-the-error-and-its-meaning-for-lhba-operations." class="level3">
<h3 class="anchored" data-anchor-id="prepare-the-data-as-necessary-and-train-a-model-to-predict-home-selling-prices-making-sure-to-evaluate-its-performance-on-the-test-data-and-interpret-the-error-and-its-meaning-for-lhba-operations.">Prepare the data as necessary and train a model to predict home selling prices, making sure to evaluate its performance on the test data and interpret the error and its meaning for LHBA operations.</h3>
<section id="exploratory-data-analysis" class="level4">
<h4 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#add together lot and building value to get total appraised value</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>pre<span class="sc">$</span>Value <span class="ot">&lt;-</span> pre<span class="sc">$</span>LandValue <span class="sc">+</span> pre<span class="sc">$</span>BuildingValue</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>post<span class="sc">$</span>Value <span class="ot">&lt;-</span> post<span class="sc">$</span>LandValue <span class="sc">+</span> post<span class="sc">$</span>BuildingValue</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>market<span class="sc">$</span>Value <span class="ot">&lt;-</span> market<span class="sc">$</span>LandValue <span class="sc">+</span> market<span class="sc">$</span>BuildingValue</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">data =</span> pre, <span class="fu">aes</span>(<span class="at">y =</span> Value, <span class="at">x =</span> <span class="st">"Pre-crisis"</span>)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">data =</span> post, <span class="fu">aes</span>(<span class="at">y =</span> Value, <span class="at">x =</span> <span class="st">"Post-crisis"</span>)) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">data =</span> market, <span class="fu">aes</span>(<span class="at">y =</span> Value, <span class="at">x =</span> <span class="st">"Current market"</span>)) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Assessed building and land value before and after 2008 financial crisis"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LHBA-House-Pricing-Regression_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Median assessed values from before and after the financial crisis, as well as current market listings, are not significantly different.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">data =</span>pre, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">"Pre-crisis"</span>, <span class="at">y =</span> Price)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">data =</span>post, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">"Post-crisis"</span>, <span class="at">y =</span> Price)) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Housing sale prices before and after 2008 financial crisis"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LHBA-House-Pricing-Regression_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>pre<span class="sc">$</span>Discrepancy <span class="ot">&lt;-</span> pre<span class="sc">$</span>Price <span class="sc">-</span> pre<span class="sc">$</span>Value</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>post<span class="sc">$</span>Discrepancy <span class="ot">&lt;-</span> post<span class="sc">$</span>Price <span class="sc">-</span> post<span class="sc">$</span>Value</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">data =</span> pre, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">"Pre-crisis"</span>, <span class="at">y =</span> Discrepancy)) <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">data =</span> post, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">"Post-crisis"</span>, <span class="at">y =</span> Discrepancy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LHBA-House-Pricing-Regression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>pre_tbl <span class="ot">&lt;-</span> pre <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(Value, Price, Discrepancy)) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(mean)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>post_tbl <span class="ot">&lt;-</span> post <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(Value, Price, Discrepancy)) <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(mean)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>tbl <span class="ot">&lt;-</span> <span class="fu">rbind</span>(pre_tbl, post_tbl, <span class="at">make.row.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(tbl) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Pre-crisis"</span>, <span class="st">"Post-crisis"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>tbl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Value    Price Discrepancy
Pre-crisis  114986.2 116202.4    1216.173
Post-crisis 118172.8 113594.1   -4578.709</code></pre>
</div>
</div>
<p>Before the crisis, the mean home price was higher than the mean home value, and the opposite was true for after the crisis. This means that houses in the area went from being sold for, on average, $1216 over county-assessed value, to being sold for, on average, $4579 under county-assessed value.</p>
</section>
<section id="data-pre-processing" class="level4">
<h4 class="anchored" data-anchor-id="data-pre-processing">Data Pre-processing</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pre)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Property        LandValue      BuildingValue        Acres      
 Min.   :   1.0   Min.   :  2300   Min.   :  4700   Min.   :0.050  
 1st Qu.: 495.2   1st Qu.: 16000   1st Qu.: 62000   1st Qu.:0.160  
 Median : 989.5   Median : 20800   Median : 86000   Median :0.180  
 Mean   : 989.5   Mean   : 22167   Mean   : 92819   Mean   :0.223  
 3rd Qu.:1483.8   3rd Qu.: 27100   3rd Qu.:111400   3rd Qu.:0.230  
 Max.   :1978.0   Max.   :124500   Max.   :552300   Max.   :5.570  
   AboveSpace      Basement           Deck            Baths      
 Min.   : 412   Min.   :   0.0   Min.   :  0.00   Min.   :0.000  
 1st Qu.: 864   1st Qu.:   0.0   1st Qu.:  0.00   1st Qu.:1.000  
 Median :1052   Median :   0.0   Median :  0.00   Median :1.000  
 Mean   :1161   Mean   : 126.4   Mean   : 76.67   Mean   :1.263  
 3rd Qu.:1372   3rd Qu.: 220.0   3rd Qu.:132.00   3rd Qu.:1.000  
 Max.   :4414   Max.   :1842.0   Max.   :980.00   Max.   :4.000  
    Toilets         Fireplaces          Beds           Rooms      
 Min.   :0.0000   Min.   :0.0000   Min.   :1.000   Min.   :1.000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:2.000   1st Qu.:2.000  
 Median :0.0000   Median :0.0000   Median :3.000   Median :3.000  
 Mean   :0.2437   Mean   :0.3038   Mean   :2.701   Mean   :2.709  
 3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:3.000   3rd Qu.:3.000  
 Max.   :2.0000   Max.   :3.0000   Max.   :7.000   Max.   :8.000  
       AC              Age              Car         PoorCondition    
 Min.   :0.0000   Min.   :  1.00   Min.   :  0.00   Min.   :0.00000  
 1st Qu.:1.0000   1st Qu.: 47.40   1st Qu.:  0.00   1st Qu.:0.00000  
 Median :1.0000   Median : 59.70   Median :  0.00   Median :0.00000  
 Mean   :0.7872   Mean   : 61.57   Mean   : 72.49   Mean   :0.06067  
 3rd Qu.:1.0000   3rd Qu.: 84.30   3rd Qu.:  0.00   3rd Qu.:0.00000  
 Max.   :1.0000   Max.   :139.10   Max.   :997.00   Max.   :1.00000  
 GoodCondition       Price            Value         Discrepancy    
 Min.   :0.000   Min.   :  5891   Min.   : 13700   Min.   :-75819  
 1st Qu.:0.000   1st Qu.: 82477   1st Qu.: 79825   1st Qu.: -9052  
 Median :1.000   Median :112789   Median :107750   Median :  2106  
 Mean   :0.639   Mean   :116202   Mean   :114986   Mean   :  1216  
 3rd Qu.:1.000   3rd Qu.:138046   3rd Qu.:135900   3rd Qu.: 12490  
 Max.   :1.000   Max.   :664874   Max.   :676800   Max.   : 59400  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(post)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Property      LandValue      BuildingValue        Acres       
 Min.   :3979   Min.   :  1900   Min.   :  2500   Min.   :0.0000  
 1st Qu.:4393   1st Qu.: 16600   1st Qu.: 65400   1st Qu.:0.1600  
 Median :4807   Median : 21700   Median : 88700   Median :0.1800  
 Mean   :4807   Mean   : 23165   Mean   : 95008   Mean   :0.2321  
 3rd Qu.:5221   3rd Qu.: 28100   3rd Qu.:113500   3rd Qu.:0.2400  
 Max.   :5635   Max.   :132900   Max.   :483300   Max.   :3.3000  
   AboveSpace      Basement           Deck            Baths      
 Min.   : 400   Min.   :   0.0   Min.   :   0.0   Min.   :0.000  
 1st Qu.: 880   1st Qu.:   0.0   1st Qu.:   0.0   1st Qu.:1.000  
 Median :1060   Median :   0.0   Median :   0.0   Median :1.000  
 Mean   :1167   Mean   : 131.6   Mean   :  77.1   Mean   :1.272  
 3rd Qu.:1370   3rd Qu.: 250.0   3rd Qu.: 140.0   3rd Qu.:1.000  
 Max.   :3979   Max.   :2100.0   Max.   :1476.0   Max.   :4.000  
    Toilets         Fireplaces          Beds           Rooms       
 Min.   :0.0000   Min.   :0.0000   Min.   :1.000   Min.   : 1.000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:2.000   1st Qu.: 2.000  
 Median :0.0000   Median :0.0000   Median :3.000   Median : 2.000  
 Mean   :0.2396   Mean   :0.3144   Mean   :2.678   Mean   : 2.684  
 3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:3.000   3rd Qu.: 3.000  
 Max.   :2.0000   Max.   :3.0000   Max.   :5.000   Max.   :10.000  
       AC              Age              Car         PoorCondition    
 Min.   :0.0000   Min.   :  1.10   Min.   :  0.00   Min.   :0.00000  
 1st Qu.:1.0000   1st Qu.: 48.20   1st Qu.:  0.00   1st Qu.:0.00000  
 Median :1.0000   Median : 59.80   Median :  0.00   Median :0.00000  
 Mean   :0.8021   Mean   : 61.57   Mean   : 74.38   Mean   :0.07845  
 3rd Qu.:1.0000   3rd Qu.: 84.70   3rd Qu.:  0.00   3rd Qu.:0.00000  
 Max.   :1.0000   Max.   :146.50   Max.   :984.00   Max.   :1.00000  
 GoodCondition        Price            Value         Discrepancy    
 Min.   :0.0000   Min.   : 10453   Min.   : 18700   Min.   :-64749  
 1st Qu.:0.0000   1st Qu.: 81249   1st Qu.: 84400   1st Qu.:-14500  
 Median :1.0000   Median :111081   Median :111400   Median : -3368  
 Mean   :0.6071   Mean   :113594   Mean   :118173   Mean   : -4579  
 3rd Qu.:1.0000   3rd Qu.:135021   3rd Qu.:139300   3rd Qu.:  6722  
 Max.   :1.0000   Max.   :527404   Max.   :560000   Max.   : 61028  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(market)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Property      LandValue      BuildingValue        Acres       
 Min.   :3636   Min.   :  2800   Min.   :  6000   Min.   :0.0570  
 1st Qu.:4136   1st Qu.: 15000   1st Qu.: 59000   1st Qu.:0.1537  
 Median :4636   Median : 19500   Median : 81300   Median :0.1780  
 Mean   :4636   Mean   : 21109   Mean   : 87762   Mean   :0.2238  
 3rd Qu.:5135   3rd Qu.: 26025   3rd Qu.:106600   3rd Qu.:0.2310  
 Max.   :5635   Max.   :132900   Max.   :576600   Max.   :3.8500  
   AboveSpace      Basement         Deck             Baths          Toilets   
 Min.   : 412   Min.   :   0   Min.   :   0.00   Min.   :1.000   Min.   :0.0  
 1st Qu.: 864   1st Qu.:   0   1st Qu.:   0.00   1st Qu.:1.000   1st Qu.:0.0  
 Median :1040   Median :   0   Median :   0.00   Median :1.000   Median :0.0  
 Mean   :1142   Mean   : 113   Mean   :  72.47   Mean   :1.239   Mean   :0.2  
 3rd Qu.:1330   3rd Qu.: 141   3rd Qu.: 120.00   3rd Qu.:1.000   3rd Qu.:0.0  
 Max.   :5112   Max.   :1400   Max.   :1476.00   Max.   :4.000   Max.   :2.0  
   Fireplaces          Beds           Rooms             AC        
 Min.   :0.0000   Min.   :1.000   Min.   :1.000   Min.   :0.0000  
 1st Qu.:0.0000   1st Qu.:2.000   1st Qu.:2.000   1st Qu.:1.0000  
 Median :0.0000   Median :3.000   Median :2.000   Median :1.0000  
 Mean   :0.2675   Mean   :2.658   Mean   :2.664   Mean   :0.7715  
 3rd Qu.:0.0000   3rd Qu.:3.000   3rd Qu.:3.000   3rd Qu.:1.0000  
 Max.   :3.0000   Max.   :6.000   Max.   :8.000   Max.   :1.0000  
      Age                Car          PoorCondition   GoodCondition  
 Min.   :   2.743   Min.   :   0.00   Min.   :0.000   Min.   :0.000  
 1st Qu.:  51.775   1st Qu.:   0.00   1st Qu.:0.000   1st Qu.:0.000  
 Median :  62.784   Median :   0.00   Median :0.000   Median :1.000  
 Mean   :  66.449   Mean   :  67.08   Mean   :0.072   Mean   :0.643  
 3rd Qu.:  88.050   3rd Qu.:   0.00   3rd Qu.:0.000   3rd Qu.:1.000  
 Max.   :1375.655   Max.   :1000.00   Max.   :1.000   Max.   :1.000  
     Price       Value       
 Min.   :0   Min.   : 12100  
 1st Qu.:0   1st Qu.: 75175  
 Median :0   Median :102000  
 Mean   :0   Mean   :108871  
 3rd Qu.:0   3rd Qu.:129525  
 Max.   :0   Max.   :648200  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>pre <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">funs</span>(<span class="fu">sum</span>(<span class="fu">is.na</span>(.))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Property LandValue BuildingValue Acres AboveSpace Basement Deck Baths Toilets
1        0         0             0     0          0        0    0     0       0
  Fireplaces Beds Rooms AC Age Car PoorCondition GoodCondition Price Value
1          0    0     0  0   0   0             0             0     0     0
  Discrepancy
1           0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>post <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">funs</span>(<span class="fu">sum</span>(<span class="fu">is.na</span>(.))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Property LandValue BuildingValue Acres AboveSpace Basement Deck Baths Toilets
1        0         0             0     0          0        0    0     0       0
  Fireplaces Beds Rooms AC Age Car PoorCondition GoodCondition Price Value
1          0    0     0  0   0   0             0             0     0     0
  Discrepancy
1           0</code></pre>
</div>
</div>
<p>There are no NA values in our datasets. Some numerical variables, like Basement and Deck, have 0’s, which represents homes which don’t have basements or decks. There are also 0’s in factor type variables like PoorCondition and GoodCondition.</p>
<section id="factor-variables" class="level5">
<h5 class="anchored" data-anchor-id="factor-variables">Factor Variables</h5>
</section>
<section id="bathrooms" class="level5">
<h5 class="anchored" data-anchor-id="bathrooms">Bathrooms</h5>
<p>There are 2 bathroom columns, Baths and Toilets. Baths is the number of full baths, toilets is the number of half baths. We can add these together by multiplying the number of Toilets by .5 and adding that number to Baths.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#pre$Baths &lt;- pre$Baths + 0.5*pre$Toilets</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co">#post$Baths &lt;- post$Baths + 0.5*post$Toilets</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co">#market$Baths &lt;- market$Baths + 0.5*market$Toilets</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="normalizing-numerical-variables" class="level5">
<h5 class="anchored" data-anchor-id="normalizing-numerical-variables">Normalizing Numerical Variables</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>normalize <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>((x<span class="sc">-</span><span class="fu">min</span>(x))<span class="sc">/</span>(<span class="fu">max</span>(x)<span class="sc">-</span><span class="fu">min</span>(x)))</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co">#saving unscaled version of post</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>post_unscaled <span class="ot">&lt;-</span> post</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> post <span class="sc">%&gt;%</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">vars</span>(Value, Acres, AboveSpace, Basement, Deck, Baths, Toilets, Fireplaces, Beds, Rooms, Age, Car), normalize)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>pre <span class="ot">&lt;-</span> pre <span class="sc">%&gt;%</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">vars</span>(Value, Acres, AboveSpace, Basement, Deck, Baths, Toilets, Fireplaces, Beds, Rooms, Age, Car), normalize)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>market <span class="ot">&lt;-</span> market <span class="sc">%&gt;%</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">vars</span>(Value, Acres, AboveSpace, Basement, Deck, Baths, Toilets, Fireplaces, Beds, Rooms, Age, Car), normalize)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dropping-columns" class="level5">
<h5 class="anchored" data-anchor-id="dropping-columns">Dropping Columns</h5>
<p>columns to drop:</p>
<p>Value (created for EDA)</p>
<p>Discrepancy (created for EDA)</p>
<p>PoorCondition, GoodCondition, AC (categorical variables – KNN regression requires numerical variables. Assigning 1 and 0 as numerical values for these variables led to significantly larger residuals.)</p>
<p>Property (ID variable)</p>
<p>Toilets (we incorporated this into Baths)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>pre <span class="ot">&lt;-</span> pre <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Value, PoorCondition, Property, Discrepancy, AC, GoodCondition))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> post <span class="sc">%&gt;%</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Value, PoorCondition, Property, Discrepancy, AC, GoodCondition))</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>market <span class="ot">&lt;-</span> market <span class="sc">%&gt;%</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Value, PoorCondition, Property, AC, GoodCondition))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="building-the-model" class="level4">
<h4 class="anchored" data-anchor-id="building-the-model">Building the Model</h4>
<p>We will use a KNN regression model for this problem. KNN is, essentially, finding “neighbors” (other observations with similar predictor values), and making predictions based on those neighbors. This is useful as housing prices are market dependent, so the sale price should theoretically be similar between houses with similar stats.</p>
<p>We will be using the post-crisis dataset to train and test our model. Once we are happy with our model’s accuracy, we will use it to make predictions on the current market dataset to provide to LHBA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">createDataPartition</span>(post<span class="sc">$</span>Price, <span class="at">p =</span> <span class="fl">0.7</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>training <span class="ot">=</span> post[samp, ]</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>testing <span class="ot">=</span> post[<span class="sc">-</span>samp,]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(samp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>x_train <span class="ot">&lt;-</span> training <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>Price)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>y_train <span class="ot">&lt;-</span> training<span class="sc">$</span>Price</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>x_test <span class="ot">&lt;-</span> testing <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>Price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>k_vals <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>k <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>rmse_vals <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> k_vals){</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">knn.reg</span>(<span class="at">train =</span> x_train, <span class="at">test =</span> x_test, <span class="at">y =</span> y_train, <span class="at">k =</span> k)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((model<span class="sc">$</span>pred <span class="sc">-</span> testing<span class="sc">$</span>Price)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>rmse_vals <span class="ot">&lt;-</span> <span class="fu">append</span>(rmse_vals, rmse)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>printrmse <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"RMSE for k="</span>, k, <span class="st">": "</span>, rmse)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(printrmse)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> k <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "RMSE for k=3: 21285.4330837433"
[1] "RMSE for k=5: 20784.0017182233"
[1] "RMSE for k=6: 20707.7953587703"
[1] "RMSE for k=7: 20459.8920154909"
[1] "RMSE for k=8: 20675.7000234096"
[1] "RMSE for k=10: 20733.6428491732"
[1] "RMSE for k=15: 21341.5642629935"
[1] "RMSE for k=20: 22169.9868568731"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> k_vals, <span class="at">y =</span> rmse_vals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LHBA-House-Pricing-Regression_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The k value that produces the lowest RMSE is k=7. This means the prediction for each observation in the test set is the mean of the seven nearest observations in the training set.</p>
<section id="evaluating-the-final-model" class="level5">
<h5 class="anchored" data-anchor-id="evaluating-the-final-model">Evaluating the Final Model</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>final_model <span class="ot">&lt;-</span> <span class="fu">knn.reg</span>(<span class="at">train =</span> x_train, <span class="at">test =</span> x_test, <span class="at">y =</span> y_train, <span class="at">k =</span> <span class="dv">7</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">createDataPartition</span>(post_unscaled<span class="sc">$</span>Price, <span class="at">p =</span> <span class="fl">0.7</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>testing_unscaled <span class="ot">=</span> post_unscaled[<span class="sc">-</span>samp,]</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(samp)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>testing_unscaled<span class="sc">$</span>pred <span class="ot">&lt;-</span> final_model<span class="sc">$</span>pred</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>testing_unscaled<span class="sc">$</span>model_resid <span class="ot">&lt;-</span> testing_unscaled<span class="sc">$</span>pred <span class="sc">-</span> testing_unscaled<span class="sc">$</span>Price</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>testing_unscaled<span class="sc">$</span>value <span class="ot">&lt;-</span> testing_unscaled<span class="sc">$</span>BuildingValue <span class="sc">+</span> testing_unscaled<span class="sc">$</span>LandValue</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>testing_unscaled<span class="sc">$</span>appraisal_resid <span class="ot">&lt;-</span> testing_unscaled<span class="sc">$</span>value <span class="sc">-</span> testing_unscaled<span class="sc">$</span>Price</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="co">#abs values for resid comparison</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>testing_unscaled<span class="sc">$</span>abs_model_resid <span class="ot">&lt;-</span> <span class="fu">abs</span>(testing_unscaled<span class="sc">$</span>model_resid)</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>testing_unscaled<span class="sc">$</span>abs_appraisal_resid <span class="ot">&lt;-</span> <span class="fu">abs</span>(testing_unscaled<span class="sc">$</span>appraisal_resid)</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>test_tbl <span class="ot">&lt;-</span> testing_unscaled <span class="sc">%&gt;%</span></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(value, Price, model_resid, appraisal_resid, abs_model_resid, abs_appraisal_resid)) <span class="sc">%&gt;%</span></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(mean)</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>test_tbl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     value    Price model_resid appraisal_resid abs_model_resid
1 119068.6 114504.9   -471.5853        4563.648        15492.95
  abs_appraisal_resid
1            15285.16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>rmse_model <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((final_model<span class="sc">$</span>pred <span class="sc">-</span> testing_unscaled<span class="sc">$</span>Price)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>rmse_appraisal <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((testing_unscaled<span class="sc">$</span>value <span class="sc">-</span> testing_unscaled<span class="sc">$</span>Price)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>rmse_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20459.89</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>rmse_appraisal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20036.64</code></pre>
</div>
</div>
<p>County appraisal values are, on average, $4564 higher than the sale price of each of the houses in the test set. The KNN model predictions are, on average, $472 under the sale price of the houses. The RMSE for the county appraisal model is 20037, and the RMSE for our KNN model is 20460.</p>
</section>
<section id="providing-predictions-for-current-market-data" class="level5">
<h5 class="anchored" data-anchor-id="providing-predictions-for-current-market-data">Providing Predictions for Current Market Data</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>market <span class="ot">&lt;-</span> market <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>Price)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>market_model <span class="ot">&lt;-</span> <span class="fu">knn.reg</span>(<span class="at">train =</span> x_train, <span class="at">test =</span> market, <span class="at">y =</span> y_train, <span class="at">k =</span> <span class="dv">7</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>market<span class="sc">$</span>pred <span class="ot">&lt;-</span> market_model<span class="sc">$</span>pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>