<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Sarah Silver test - National Veterans Organization Donor Classification</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/personal_logo.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sarah Silver test</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html" rel="" target="">
 <span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html" rel="" target="">
 <span class="menu-text">Resume</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">National Veterans Organization Donor Classification</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="write-a-paragraph-explaining-why-classification-is-the-right-approach-for-the-nvos-problem." class="level4">
<h4 class="anchored" data-anchor-id="write-a-paragraph-explaining-why-classification-is-the-right-approach-for-the-nvos-problem.">1. Write a paragraph explaining why classification is the right approach for the NVO’s problem.</h4>
<p>The NVO is trying to determine whether a person will respond or not respond, which is effectively sorting their donor list into two categories. Classification is a data mining technique which predicts the category of an observation based on predictor variables. By classifying donors into classes respond/not respond, the NVO can tailor their email campaign accordingly, whether this means focusing all of their emails on likely donors, or tailoring specific emails based on how likely the donor is to reply. By using a data-driven approach to their marketing campaign, the NVO can improve their response rate, and ultimately increase the amount of donations they receive.</p>
</section>
<section id="write-a-paragraph-explaining-how-nvo-could-use-the-classifier-you-build-to-identify-potential-donors.-why-could-it-be-better-than-what-theyve-been-doing" class="level4">
<h4 class="anchored" data-anchor-id="write-a-paragraph-explaining-how-nvo-could-use-the-classifier-you-build-to-identify-potential-donors.-why-could-it-be-better-than-what-theyve-been-doing">2. Write a paragraph explaining how NVO could use the classifier you build to identify potential donors. Why could it be better than what they’ve been doing?</h4>
<p>By using the classification model I will build for determining whether a donor will respond to an email or not, based on the factors most correlated with response, including demographics and information about previous donations, the NVO will be able to process donor data effectively and efficiently in order to maximize responses using the least resources possible. Nonprofits often will send out emails or physical mailings to everyone on their lists, wasting their resources on advertisements that will end up in the trash or in the recipient’s spam folder. By leveraging a classification model, the NVO will be able to only send mail/email to those who are likely to respond, allowing them to increase their response rate and save resources in the process.</p>
</section>
<section id="write-a-paragraph-explaining-which-measures-from-the-confusion-matrix-youll-use-to-evaluate-the-classifier-performance-and-how-they-relate-to-important-areas-like-mailer-response-rate-and-maximizing-donation-opportunities." class="level4">
<h4 class="anchored" data-anchor-id="write-a-paragraph-explaining-which-measures-from-the-confusion-matrix-youll-use-to-evaluate-the-classifier-performance-and-how-they-relate-to-important-areas-like-mailer-response-rate-and-maximizing-donation-opportunities.">3. Write a paragraph explaining which measures from the confusion matrix you’ll use to evaluate the classifier performance and how they relate to important areas like mailer response rate, and maximizing donation opportunities.</h4>
<p>I plan on using precision, recall/sensitivity, and specificity to evaluate the performance of my classifier.</p>
<ul>
<li><p>Precision will measure the proportion of predicted responders will actually respond. <strong>High precision indicates that when the classifier predicts a positive outcome, it is likely to be correct.</strong> This leaves a high-precision model open to missing actual positive cases.</p></li>
<li><p>Recall/sensitivity/true positive rate will measure the proportion of actual responders that we predicted would respond. This is important, as we want to contact everyone who will respond, and avoid missing out on potential donations. <strong>High sensitivity indicates that the classifier is good at identifying all positive cases</strong>, but it may also include false positives.</p></li>
<li><p>Specificity/true negative rate will measure the proportion of actual non-responders we predicted would not respond. This is important as a high specificity ensures that we are not wasting resources on those who won’t respond. <strong>High specificity indicates that the classifier is good at identifying all negative cases,</strong> but it may also include false negatives.</p></li>
<li><p>F1-score is a metric defined as the harmonic mean between precision and recall. This helps us make sure our model is balanced in terms of precision and recall – if these two values are significantly different, the F1-score will be low, but if they’re similar, the F1-score will be high. F1-score is especially important in a model where a false positive and false negative have relatively equal impacts, and therefore our best model will balance the two.</p></li>
</ul>
<p><em>After perusing and cleaning the data, decide on the most useful features and build the two classification models - remembering to follow proper principles (i.e., data partitioning, cross validation, etc.).</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dummy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>dummy 0.1.3
dummyNews()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice

Attaching package: 'caret'

The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performanceEstimation)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Type 'citation("pROC")' for a citation.

Attaching package: 'pROC'

The following objects are masked from 'package:stats':

    cov, smooth, var</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix

Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack

Loaded glmnet 4.1-8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(yardstick)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'yardstick'

The following objects are masked from 'package:caret':

    precision, recall, sensitivity, specificity

The following object is masked from 'package:readr':

    spec</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DALEX)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome to DALEX (version: 2.4.3).
Find examples and detailed introduction at: http://ema.drwhy.ai/
Additional features will be available after installation of: ggpubr.
Use 'install_dependencies()' to get all suggested dependencies

Attaching package: 'DALEX'

The following object is masked from 'package:dplyr':

    explain</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>donors_orig <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"donors.csv"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"donors.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(donors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age numberChildren incomeRating wealthRating mailOrderPurchases
1  60             NA           NA           NA                  0
2  46              1            6            9                 16
3  NA             NA            3            1                  2
4  70             NA            1            4                  2
5  78              1            3            2                 60
6  NA             NA           NA           NA                  0
  totalGivingAmount numberGifts smallestGiftAmount largestGiftAmount
1               240          31                  5                12
2                47           3                 10                25
3               202          27                  2                16
4               109          16                  2                11
5               254          37                  3                15
6                51           4                 10                16
  averageGiftAmount yearsSinceFirstDonation monthsSinceLastDonation
1          7.741935                       8                      14
2         15.666667                       3                      14
3          7.481481                       7                      14
4          6.812500                      10                      14
5          6.864865                      11                      13
6         12.750000                       3                      20
  inHouseDonor plannedGivingDonor sweepstakesDonor P3Donor state urbanicity
1        FALSE              FALSE            FALSE   FALSE    IL       town
2        FALSE              FALSE            FALSE   FALSE    CA     suburb
3        FALSE              FALSE            FALSE   FALSE    NC      rural
4        FALSE              FALSE            FALSE   FALSE    CA      rural
5         TRUE              FALSE            FALSE    TRUE    FL     suburb
6        FALSE              FALSE            FALSE   FALSE    AL       town
  socioEconomicStatus isHomeowner gender respondedMailing
1             average          NA female            FALSE
2             highest        TRUE   male            FALSE
3             average          NA   male            FALSE
4             average          NA female            FALSE
5             average        TRUE female            FALSE
6             average          NA   &lt;NA&gt;            FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(donors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age        numberChildren   incomeRating    wealthRating  
 Min.   : 1.00   Min.   :1.00    Min.   :1.000   Min.   :0.00   
 1st Qu.:48.00   1st Qu.:1.00    1st Qu.:2.000   1st Qu.:3.00   
 Median :62.00   Median :1.00    Median :4.000   Median :6.00   
 Mean   :61.61   Mean   :1.53    Mean   :3.886   Mean   :5.35   
 3rd Qu.:75.00   3rd Qu.:2.00    3rd Qu.:5.000   3rd Qu.:8.00   
 Max.   :98.00   Max.   :7.00    Max.   :7.000   Max.   :9.00   
 NA's   :23665   NA's   :83026   NA's   :21286   NA's   :44732  
 mailOrderPurchases totalGivingAmount  numberGifts      smallestGiftAmount
 Min.   :  0.000    Min.   :  13.0    Min.   :  1.000   Min.   :   0.000  
 1st Qu.:  0.000    1st Qu.:  40.0    1st Qu.:  3.000   1st Qu.:   3.000  
 Median :  0.000    Median :  78.0    Median :  7.000   Median :   5.000  
 Mean   :  3.321    Mean   : 104.5    Mean   :  9.602   Mean   :   7.934  
 3rd Qu.:  3.000    3rd Qu.: 131.0    3rd Qu.: 13.000   3rd Qu.:  10.000  
 Max.   :241.000    Max.   :9485.0    Max.   :237.000   Max.   :1000.000  
                                                                          
 largestGiftAmount averageGiftAmount  yearsSinceFirstDonation
 Min.   :   5      Min.   :   1.286   Min.   : 0.000         
 1st Qu.:  14      1st Qu.:   8.385   1st Qu.: 2.000         
 Median :  17      Median :  11.636   Median : 5.000         
 Mean   :  20      Mean   :  13.348   Mean   : 5.596         
 3rd Qu.:  23      3rd Qu.:  15.478   3rd Qu.: 9.000         
 Max.   :5000      Max.   :1000.000   Max.   :13.000         
                                                             
 monthsSinceLastDonation inHouseDonor    plannedGivingDonor sweepstakesDonor
 Min.   : 0.00           Mode :logical   Mode :logical      Mode :logical   
 1st Qu.:12.00           FALSE:88709     FALSE:95298        FALSE:93795     
 Median :14.00           TRUE :6703      TRUE :114          TRUE :1617      
 Mean   :14.36                                                              
 3rd Qu.:17.00                                                              
 Max.   :23.00                                                              
                                                                            
  P3Donor           state            urbanicity        socioEconomicStatus
 Mode :logical   Length:95412       Length:95412       Length:95412       
 FALSE:93395     Class :character   Class :character   Class :character   
 TRUE :2017      Mode  :character   Mode  :character   Mode  :character   
                                                                          
                                                                          
                                                                          
                                                                          
 isHomeowner       gender          respondedMailing
 Mode:logical   Length:95412       Mode :logical   
 TRUE:52354     Class :character   FALSE:90569     
 NA's:43058     Mode  :character   TRUE :4843      
                                                   
                                                   
                                                   
                                                   </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">apply</span>(<span class="at">X =</span> <span class="fu">is.na</span>(donors), <span class="at">MARGIN =</span> <span class="dv">2</span>, <span class="at">FUN =</span> sum))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    age          numberChildren            incomeRating 
                  23665                   83026                   21286 
           wealthRating      mailOrderPurchases       totalGivingAmount 
                  44732                       0                       0 
            numberGifts      smallestGiftAmount       largestGiftAmount 
                      0                       0                       0 
      averageGiftAmount yearsSinceFirstDonation monthsSinceLastDonation 
                      0                       0                       0 
           inHouseDonor      plannedGivingDonor        sweepstakesDonor 
                      0                       0                       0 
                P3Donor                   state              urbanicity 
                      0                       0                    2316 
    socioEconomicStatus             isHomeowner                  gender 
                   2316                   43058                    4676 
       respondedMailing 
                      0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(donors))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 88455</code></pre>
</div>
</div>
<section id="dealing-with-missing-values" class="level5">
<h5 class="anchored" data-anchor-id="dealing-with-missing-values">Dealing with missing values</h5>
<p>We have many missing values in our data – 88,455 out of 95412 observations have at least one missing value. For continuous variables, we will perform median imputation. For categorical variables, we will either drop columns or replace NA’s with the most common class.</p>
<p>numerical variables with NA’s: age</p>
<p>categorical variables with NA’s: numberChildren (mostly NA’s), income rating, wealth rating (about half NA’s), urbanicity, socioEconomicStatus, isHomeowner (about half NA’s), gender</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(donors<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   1.00   48.00   62.00   61.61   75.00   98.00   23665 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(donors<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>median imputation for age variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(age),</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">median</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                           age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(donors<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.00   52.00   62.00   61.71   71.00   98.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(donors<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>EDA for categorical variables with NA’s:</p>
</section>
<section id="ishomeowner" class="level5">
<h5 class="anchored" data-anchor-id="ishomeowner">isHomeowner</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>donors <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(isHomeowner, respondedMailing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  isHomeowner respondedMailing     n
1        TRUE            FALSE 49646
2        TRUE             TRUE  2708
3          NA            FALSE 40923
4          NA             TRUE  2135</code></pre>
</div>
</div>
<p>5.17% response rate for isHomeowner ==True</p>
<p>4.96% response rate for isHomeowner == NA</p>
<p>The only value for isHomeowner is TRUE. Even if we treat the NA’s as their own category, the response rate is not significantly different for the two groups. We should drop the column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>isHomeowner)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="numberchildren" class="level5">
<h5 class="anchored" data-anchor-id="numberchildren">numberChildren</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>donors <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(numberChildren)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  numberChildren     n
1              1  7792
2              2  3110
3              3  1101
4              4   316
5              5    59
6              6     7
7              7     1
8             NA 83026</code></pre>
</div>
</div>
<p>Most of the values for numberChildren are missing. We should drop the column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>numberChildren)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="incomerating" class="level5">
<h5 class="anchored" data-anchor-id="incomerating">incomeRating</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>incomePred <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(incomeRating, respondedMailing) <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(incomeRating) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">count =</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(respondedMailing) <span class="sc">%&gt;%</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">respRate =</span> n<span class="sc">/</span>count) <span class="sc">%&gt;%</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(respondedMailing <span class="sc">==</span> <span class="cn">TRUE</span>)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>incomePred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
# Groups:   respondedMailing [1]
  incomeRating respondedMailing     n count respRate
         &lt;int&gt; &lt;lgl&gt;            &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;
1            1 TRUE               376  9022   0.0417
2            2 TRUE               632 13114   0.0482
3            3 TRUE               423  8558   0.0494
4            4 TRUE               640 12732   0.0503
5            5 TRUE               812 15451   0.0526
6            6 TRUE               431  7778   0.0554
7            7 TRUE               426  7471   0.0570
8           NA TRUE              1103 21286   0.0518</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(donors<span class="sc">$</span>incomeRating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> incomePred<span class="sc">$</span>incomeRating, <span class="at">y =</span> incomePred<span class="sc">$</span>respRate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>incomeRating is positively correlated with the response rate, so we should keep the variable, even though it has a significant number of NA’s. Conveniently, the response rate of the NA values is right in between the response rate for incomeLevel 4 and 5, and 5 is the most commonly occurring value. We can feel confident that replacing our NA’s with the mode will not have a drastic effect on our model’s performance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">incomeRating =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(incomeRating),</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                           <span class="dv">5</span>,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                           incomeRating))</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(donors<span class="sc">$</span>incomeRating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="wealthrating" class="level5">
<h5 class="anchored" data-anchor-id="wealthrating">wealthRating</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>wealthPred <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(wealthRating, respondedMailing) <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(wealthRating) <span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">count =</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(respondedMailing) <span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">respRate =</span> n<span class="sc">/</span>count) <span class="sc">%&gt;%</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(respondedMailing <span class="sc">==</span> <span class="cn">TRUE</span>)</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>wealthPred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 5
# Groups:   respondedMailing [1]
   wealthRating respondedMailing     n count respRate
          &lt;int&gt; &lt;lgl&gt;            &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;
 1            0 TRUE               111  2413   0.0460
 2            1 TRUE               162  3454   0.0469
 3            2 TRUE               202  4085   0.0494
 4            3 TRUE               216  4237   0.0510
 5            4 TRUE               237  4810   0.0493
 6            5 TRUE               254  5280   0.0481
 7            6 TRUE               323  5825   0.0555
 8            7 TRUE               330  6198   0.0532
 9            8 TRUE               350  6793   0.0515
10            9 TRUE               423  7585   0.0558
11           NA TRUE              2235 44732   0.0500</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(donors<span class="sc">$</span>wealthRating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> wealthPred<span class="sc">$</span>wealthRating, <span class="at">y =</span> wealthPred<span class="sc">$</span>respRate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The choice, whether to impute or drop this column, is trickier than the last example. The relationship between wealthRating and response rate is positively correlated, but with much more irregularity than incomeRating. Additionally, the mode of the wealthRating variable is 9, the highest possible answer. The response rate for the NA’s does not line up with the response rate for the 9’s.</p>
<p>This is also a good time to consider multicollinearity. While wealthRating and incomeRating sound like they could be representing the same thing, if we consider our dataset, our donors are likely older and often veterans, who may be retired, with low income yet with high wealth in retirement accounts and other investments. This is why the distribution of wealthRating and incomeRating are so different, and we can be sure that including both of these variables will not introduce multicollinearity into our model. We also have a variable called socioEconomicStatus, which could represent the same information as wealthRating, which could introduce multicollinearity into our model.</p>
<p>Ultimately, I have decided to drop the column. More advanced imputation techniques could be used to fix this problem but this is beyond the scope of this assignment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>wealthRating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="urbanicity-socioeconomicstatus-gender" class="level5">
<h5 class="anchored" data-anchor-id="urbanicity-socioeconomicstatus-gender">urbanicity, socioEconomicStatus, gender</h5>
<p>These three categorical variables have relatively low proportions of NA values so we don’t need to worry so much about the impact of imputation on our model’s accuracy. I will use mode imputation for all three of these variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#getmode &lt;- function(v) {</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>   <span class="co">#uniqv &lt;- unique(v)</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>   <span class="co">#uniqv[which.max(tabulate(match(v, uniqv)))]</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co">#}</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span> </span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">urbanicity =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(urbanicity), </span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"unknown"</span>, </span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>                         urbanicity)) <span class="sc">%&gt;%</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">socioEconomicStatus =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(socioEconomicStatus), </span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"unknown"</span>, </span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>                         socioEconomicStatus)) <span class="sc">%&gt;%</span></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gender =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(gender), </span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"unknown"</span>, </span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>                         gender))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="state" class="level5">
<h5 class="anchored" data-anchor-id="state">State</h5>
<p>State being a categorical variable with 50 levels may exert undue force on the model. After testing this model both with and without state, the models without state perform much better, so I’m choosing to remove it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="correlation" class="level5">
<h5 class="anchored" data-anchor-id="correlation">Correlation</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>num <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">keep</span>(is.numeric)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>corr <span class="ot">&lt;-</span> <span class="fu">cor</span>(num)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The largest correlations are between variables smallestGiftAmount, largestGiftAmount, and averageGiftAmount, as well as between numberGifts and yearsSinceFirstDonation.</p>
<p>We will remove smallestGiftAmount, largestGiftAmount, and yearsSinceFirstDonation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(<span class="st">"smallestGiftAmount"</span>, <span class="st">"largestGiftAmount"</span>, <span class="st">"yearsSinceFirstDonation"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="scaling" class="level5">
<h5 class="anchored" data-anchor-id="scaling">Scaling</h5>
<p>Lasso models are sensitive to the scale of the input features, so we need to do some scaling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>normalize <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>((x<span class="sc">-</span><span class="fu">min</span>(x))<span class="sc">/</span>(<span class="fu">max</span>(x)<span class="sc">-</span><span class="fu">min</span>(x)))</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">vars</span>(age, mailOrderPurchases, totalGivingAmount, numberGifts, averageGiftAmount, monthsSinceLastDonation), normalize)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dummies" class="level5">
<h5 class="anchored" data-anchor-id="dummies">Dummies</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>donors<span class="sc">$</span>incomeRating <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(donors<span class="sc">$</span>incomeRating)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>donors_dummies <span class="ot">&lt;-</span> <span class="fu">dummy</span>(donors)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>donors_dummies <span class="ot">&lt;-</span> donors_dummies <span class="sc">%&gt;%</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_all</span>(as.factor)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>donors_num <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span> <span class="fu">keep</span>(is.numeric)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>donors_bool <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">c</span>(<span class="st">"inHouseDonor"</span>, <span class="st">"plannedGivingDonor"</span>, <span class="st">"sweepstakesDonor"</span>, <span class="st">"respondedMailing"</span>))</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>donors_bool <span class="ot">&lt;-</span> donors_bool<span class="sc">*</span><span class="dv">1</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>donors_bool <span class="ot">&lt;-</span> donors_bool <span class="sc">%&gt;%</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_all</span>(as.factor)</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>donors_bool<span class="sc">$</span>respondedMailing <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(donors_bool<span class="sc">$</span>respondedMailing)</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>donors_model <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(donors_dummies, donors_num, donors_bool)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="build-a-logistic-lasso-model-using-cross-validation-on-the-training-data-to-select-the-best-lambda.-view-the-coefficients-at-that-chosen-lambda-and-see-what-features-are-in-the-model." class="level4">
<h4 class="anchored" data-anchor-id="build-a-logistic-lasso-model-using-cross-validation-on-the-training-data-to-select-the-best-lambda.-view-the-coefficients-at-that-chosen-lambda-and-see-what-features-are-in-the-model.">4. Build a logistic LASSO model using cross-validation on the training data to select the best $\lambda$. View the coefficients at that chosen $\lambda$ and see what features are in the model.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">createDataPartition</span>(donors_model<span class="sc">$</span>respondedMailing, <span class="at">p =</span> <span class="fl">0.7</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>lasso_train <span class="ot">=</span> donors_model[samp, ]</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>lasso_test <span class="ot">=</span> donors_model[<span class="sc">-</span>samp,]</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(samp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co">#set.seed(567)</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="co">#lasso_train_down = downSample(x = select(lasso_train, -respondedMailing),</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>                         <span class="co">#y = lasso_train$respondedMailing,</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>                         <span class="co">#yname = "respondedMailing")</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="co">#lasso_train_down %&gt;% select(respondedMailing) %&gt;% table()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>lasso_train_smote <span class="ot">&lt;-</span> <span class="fu">smote</span>(respondedMailing <span class="sc">~</span> .,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> lasso_train,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">perc.under =</span> <span class="dv">2</span>,</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">perc.over =</span> <span class="dv">3</span>)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>lasso_train_smote <span class="sc">%&gt;%</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(respondedMailing) <span class="sc">%&gt;%</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>respondedMailing
    0     1 
20346 13564 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#separate predictors and outcome</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(respondedMailing<span class="sc">~</span>., lasso_train_smote)[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> lasso_train_smote<span class="sc">$</span>respondedMailing</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>cv.lasso <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(x, y, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x, y, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">lambda =</span> cv.lasso<span class="sc">$</span>lambda.min)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="co">#regression coefficients</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>31 x 1 sparse Matrix of class "dgCMatrix"
                                        s0
(Intercept)                   4.916170e-01
incomeRating_11              -2.379194e-01
incomeRating_21              -1.523994e-01
incomeRating_31              -1.018186e-01
incomeRating_41               .           
incomeRating_51               6.201833e-02
incomeRating_61               8.782742e-02
incomeRating_71               7.080376e-02
urbanicity_city1             -1.026712e-02
urbanicity_rural1            -4.696075e-02
urbanicity_suburb1            1.352039e-02
urbanicity_town1              1.314608e-03
urbanicity_unknown1           2.057639e-01
urbanicity_urban1             .           
socioEconomicStatus_average1  .           
socioEconomicStatus_highest1  1.237479e-01
socioEconomicStatus_lowest1  -1.793663e-01
socioEconomicStatus_unknown1  1.100613e-02
gender_female1               -8.587326e-04
gender_joint1                 3.051161e-01
gender_male1                  4.245793e-03
gender_unknown1              -2.075170e-02
age                           1.009256e-01
mailOrderPurchases            2.691465e-01
totalGivingAmount            -1.396638e+00
numberGifts                   2.553341e+00
averageGiftAmount            -2.659985e+01
monthsSinceLastDonation      -1.188682e+00
inHouseDonor1                -2.519843e-01
plannedGivingDonor1           6.570808e-01
sweepstakesDonor1            -6.825118e-01</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#preds</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>x_test <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(respondedMailing <span class="sc">~</span>., lasso_test)[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>probabilities <span class="ot">&lt;-</span> model <span class="sc">%&gt;%</span> <span class="fu">predict</span>(<span class="at">newx =</span> x_test, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>predicted_classes <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(probabilities <span class="sc">&gt;</span> .<span class="dv">5</span>, <span class="st">"1"</span>, <span class="st">"0"</span>)</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="co">#accuracy</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>observed_classes <span class="ot">&lt;-</span> lasso_test<span class="sc">$</span>respondedMailing</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"Model Accuracy: "</span>, <span class="fu">mean</span>(predicted_classes <span class="sc">==</span> observed_classes))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Model Accuracy: 0.882782475019216"</code></pre>
</div>
</div>
<p>Our final accuracy is 88.3%. All variables with non-zero coefficients are included in the model.</p>
<p>By choosing a lower threshold than .5, we would allow our model to predict more positive outcomes. This would be useful if you had a limited list of donors and wanted to identify as many potential donors out of your list as possible. For this example, I’m assuming we have an effectively infinite donor base in order to maximize precision and ultimately the campaign’s response rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cv.lasso)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>cv.lasso<span class="sc">$</span>lambda.min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0007022933</code></pre>
</div>
</div>
<p>The optimal <span class="math inline">\(\lambda\)</span> is .00070.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(cv.lasso, cv.lasso<span class="sc">$</span>lambda.min)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>31 x 1 sparse Matrix of class "dgCMatrix"
                                        s1
(Intercept)                   4.926730e-01
incomeRating_11              -2.378738e-01
incomeRating_21              -1.523719e-01
incomeRating_31              -1.017770e-01
incomeRating_41               .           
incomeRating_51               6.199029e-02
incomeRating_61               8.786297e-02
incomeRating_71               7.085918e-02
urbanicity_city1             -1.072416e-02
urbanicity_rural1            -4.737981e-02
urbanicity_suburb1            1.313710e-02
urbanicity_town1              9.928947e-04
urbanicity_unknown1           2.158259e-01
urbanicity_urban1             .           
socioEconomicStatus_average1  .           
socioEconomicStatus_highest1  1.236654e-01
socioEconomicStatus_lowest1  -1.793007e-01
socioEconomicStatus_unknown1  5.132827e-04
gender_female1               -4.163493e-04
gender_joint1                 3.055695e-01
gender_male1                  4.723188e-03
gender_unknown1              -2.029743e-02
age                           1.011465e-01
mailOrderPurchases            2.686140e-01
totalGivingAmount            -1.269492e+00
numberGifts                   2.519119e+00
averageGiftAmount            -2.670599e+01
monthsSinceLastDonation      -1.188647e+00
inHouseDonor1                -2.522371e-01
plannedGivingDonor1           6.543187e-01
sweepstakesDonor1            -6.825351e-01</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(predicted_classes,observed_classes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 observed_classes
predicted_classes     0     1
                0 25055  1240
                1  2115   212</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">roc.glmnet</span>(model, </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">newx =</span> x, </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">newy =</span> y ), </span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">type=</span><span class="st">"l"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>assess <span class="ot">&lt;-</span> <span class="fu">assess.glmnet</span>(model, <span class="at">newx=</span>x, <span class="at">newy=</span>y)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>assess<span class="sc">$</span>auc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6016006
attr(,"measure")
[1] "AUC"</code></pre>
</div>
</div>
<p>AUC = .602</p>
</section>
<section id="build-a-decision-tree-model-using-cross-validation-on-the-training-data-to-select-the-best-cp-value.-use-rpart.plot-to-view-the-decision-tree.-what-key-features-does-it-use" class="level4">
<h4 class="anchored" data-anchor-id="build-a-decision-tree-model-using-cross-validation-on-the-training-data-to-select-the-best-cp-value.-use-rpart.plot-to-view-the-decision-tree.-what-key-features-does-it-use">5. Build a decision tree model using cross-validation on the training data to select the best <code>cp</code> value. Use <code>rpart.plot()</code> to view the decision tree. What key features does it use?</h4>
<section id="class-balance" class="level5">
<h5 class="anchored" data-anchor-id="class-balance">Class Balance</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>donors_model <span class="sc">%&gt;%</span> </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(respondedMailing) <span class="sc">%&gt;%</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>respondedMailing
    0     1 
90569  4843 </code></pre>
</div>
</div>
<p>Our classes are imbalanced. Only 5.3% of donors responded to the mailing. We need to take this into account in our model.</p>
</section>
<section id="data-partition" class="level5">
<h5 class="anchored" data-anchor-id="data-partition">Data Partition</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">createDataPartition</span>(donors_model<span class="sc">$</span>respondedMailing, <span class="at">p =</span> <span class="fl">0.7</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">=</span> donors_model[samp, ]</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>test <span class="ot">=</span> donors_model[<span class="sc">-</span>samp,]</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(samp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Check class balance of test and train sets:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">select</span>(respondedMailing) <span class="sc">%&gt;%</span> <span class="fu">table</span>() <span class="sc">%&gt;%</span> <span class="fu">prop.table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>respondedMailing
         0          1 
0.94922893 0.05077107 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>test <span class="sc">%&gt;%</span> <span class="fu">select</span>(respondedMailing) <span class="sc">%&gt;%</span> <span class="fu">table</span>() <span class="sc">%&gt;%</span> <span class="fu">prop.table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>respondedMailing
         0          1 
0.94926979 0.05073021 </code></pre>
</div>
</div>
<p>The degree of imbalance is similar.</p>
</section>
<section id="downsampling" class="level5">
<h5 class="anchored" data-anchor-id="downsampling">Downsampling</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>train_down <span class="ot">=</span> <span class="fu">downSample</span>(<span class="at">x =</span> <span class="fu">select</span>(train, <span class="sc">-</span>respondedMailing),</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">y =</span> train<span class="sc">$</span>respondedMailing,</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">yname =</span> <span class="st">"respondedMailing"</span>)</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>train_down <span class="sc">%&gt;%</span> <span class="fu">select</span>(respondedMailing) <span class="sc">%&gt;%</span> <span class="fu">table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>respondedMailing
   0    1 
3391 3391 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>train_smote <span class="ot">=</span> <span class="fu">smote</span>(respondedMailing <span class="sc">~</span> .,</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> train,</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">perc.under =</span> <span class="dv">2</span>,</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">perc.over =</span> <span class="fl">1.5</span>)</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>train_smote <span class="sc">%&gt;%</span></span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(respondedMailing) <span class="sc">%&gt;%</span></span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>respondedMailing
   0    1 
6782 6782 </code></pre>
</div>
</div>
</section>
<section id="decision-tree" class="level5">
<h5 class="anchored" data-anchor-id="decision-tree">Decision Tree</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">=</span> caret<span class="sc">::</span><span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>unbalanced_tree <span class="ot">=</span> <span class="fu">train</span>(respondedMailing <span class="sc">~</span> .,</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> train,</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">metric =</span> <span class="st">"Kappa"</span>,</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">trControl =</span> ctrl,</span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(<span class="at">cp =</span> <span class="fu">seq</span>(<span class="fl">0.0</span>, <span class="fl">0.03</span>, <span class="fl">0.0005</span>)))</span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(unbalanced_tree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>down_tree <span class="ot">=</span> <span class="fu">train</span>(respondedMailing <span class="sc">~</span> .,</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> train_down,</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">metric =</span> <span class="st">"Kappa"</span>,</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>                        <span class="co">#control = rpart_ctrl,</span></span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">trControl =</span> ctrl,</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(<span class="at">cp =</span> <span class="fu">seq</span>(<span class="fl">0.0</span>, <span class="fl">0.03</span>, <span class="fl">0.0005</span>)))</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(down_tree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>smote_tree <span class="ot">=</span> <span class="fu">train</span>(respondedMailing <span class="sc">~</span> .,</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> train_smote,</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">metric =</span> <span class="st">"Kappa"</span>,</span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>                        <span class="co">#control = rpart_ctrl,</span></span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">trControl =</span> ctrl,</span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(<span class="at">cp =</span> <span class="fu">seq</span>(<span class="fl">0.0</span>, <span class="fl">0.03</span>, <span class="fl">0.0005</span>)))</span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(smote_tree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(unbalanced_tree<span class="sc">$</span>finalModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: labs do not fit even at cex 0.15, there may be some overplotting</code></pre>
</div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(down_tree<span class="sc">$</span>finalModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(smote_tree<span class="sc">$</span>finalModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="evaluate-the-performance-on-test-data-and-look-at-and-describe-its-performance-according-to-your-confusion-matrix-measures." class="level4">
<h4 class="anchored" data-anchor-id="evaluate-the-performance-on-test-data-and-look-at-and-describe-its-performance-according-to-your-confusion-matrix-measures.">6. Evaluate the performance on test data and look at and describe its performance according to your confusion matrix measures.</h4>
<section id="decision-trees" class="level5">
<h5 class="anchored" data-anchor-id="decision-trees">Decision Trees</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get class predictions</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>unbalanced_test_class <span class="ot">=</span> <span class="fu">predict</span>(unbalanced_tree, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"raw"</span>)</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>down_test_class <span class="ot">=</span> <span class="fu">predict</span>(down_tree, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"raw"</span>)</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>smote_test_class <span class="ot">=</span> <span class="fu">predict</span>(smote_tree, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"raw"</span>)</span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Get probability predictions</span></span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>unbalanced_test_prob <span class="ot">=</span> <span class="fu">predict</span>(unbalanced_tree, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">2</span>]</span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>down_test_prob <span class="ot">=</span> <span class="fu">predict</span>(down_tree, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">2</span>]</span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a>smote_test_prob <span class="ot">=</span> <span class="fu">predict</span>(smote_tree, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>pred_prob <span class="ot">=</span> <span class="fu">predict</span>(smote_tree, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">2</span>]</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">"1"</span>, <span class="st">"0"</span>))</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(pred_class, test<span class="sc">$</span>respondedMailing, <span class="at">positive =</span> <span class="st">"1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction     0     1
         0 23456  1165
         1  3714   287
                                          
               Accuracy : 0.8295          
                 95% CI : (0.8251, 0.8339)
    No Information Rate : 0.9493          
    P-Value [Acc &gt; NIR] : 1               
                                          
                  Kappa : 0.0333          
                                          
 Mcnemar's Test P-Value : &lt;2e-16          
                                          
            Sensitivity : 0.19766         
            Specificity : 0.86331         
         Pos Pred Value : 0.07173         
         Neg Pred Value : 0.95268         
             Prevalence : 0.05073         
         Detection Rate : 0.01003         
   Detection Prevalence : 0.13979         
      Balanced Accuracy : 0.53048         
                                          
       'Positive' Class : 1               
                                          </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>down_prob <span class="ot">=</span> <span class="fu">predict</span>(down_tree, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">2</span>]</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>down_class <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(down_prob <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">"1"</span>, <span class="st">"0"</span>))</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(down_class, test<span class="sc">$</span>respondedMailing, <span class="at">positive =</span> <span class="st">"1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction     0     1
         0 17555   733
         1  9615   719
                                         
               Accuracy : 0.6385         
                 95% CI : (0.6329, 0.644)
    No Information Rate : 0.9493         
    P-Value [Acc &gt; NIR] : 1              
                                         
                  Kappa : 0.0363         
                                         
 Mcnemar's Test P-Value : &lt;2e-16         
                                         
            Sensitivity : 0.49518        
            Specificity : 0.64612        
         Pos Pred Value : 0.06958        
         Neg Pred Value : 0.95992        
             Prevalence : 0.05073        
         Detection Rate : 0.02512        
   Detection Prevalence : 0.36105        
      Balanced Accuracy : 0.57065        
                                         
       'Positive' Class : 1              
                                         </code></pre>
</div>
</div>
<p>The key factor in the unbalanced and downsampled trees is averageGiftAmount, and the key factor in the SMOTE tree is numberGifts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>unbalanced_cv_kappa <span class="ot">=</span> <span class="fu">mean</span>(unbalanced_tree<span class="sc">$</span>results<span class="sc">$</span>Kappa)</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>unbalanced_test_kappa <span class="ot">=</span> <span class="fu">confusionMatrix</span>(unbalanced_test_class,</span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>                                        test<span class="sc">$</span>respondedMailing,</span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">positive =</span> <span class="st">"1"</span>)<span class="sc">$</span>overall[[<span class="st">"Kappa"</span>]]</span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>unbalanced_test_auc <span class="ot">=</span> ModelMetrics<span class="sc">::</span><span class="fu">auc</span>(test<span class="sc">$</span>respondedMailing, unbalanced_test_prob)</span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a>down_cv_kappa <span class="ot">=</span> <span class="fu">mean</span>(down_tree<span class="sc">$</span>results<span class="sc">$</span>Kappa)</span>
<span id="cb100-8"><a href="#cb100-8" aria-hidden="true" tabindex="-1"></a>down_test_kappa <span class="ot">=</span> <span class="fu">confusionMatrix</span>(down_test_class,</span>
<span id="cb100-9"><a href="#cb100-9" aria-hidden="true" tabindex="-1"></a>                                  test<span class="sc">$</span>respondedMailing,</span>
<span id="cb100-10"><a href="#cb100-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">positive =</span> <span class="st">"1"</span>)<span class="sc">$</span>overall[[<span class="st">"Kappa"</span>]]</span>
<span id="cb100-11"><a href="#cb100-11" aria-hidden="true" tabindex="-1"></a>down_test_auc <span class="ot">=</span> ModelMetrics<span class="sc">::</span><span class="fu">auc</span>(test<span class="sc">$</span>respondedMailing, down_test_prob)</span>
<span id="cb100-12"><a href="#cb100-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-13"><a href="#cb100-13" aria-hidden="true" tabindex="-1"></a>smote_cv_kappa <span class="ot">=</span> <span class="fu">mean</span>(smote_tree<span class="sc">$</span>results<span class="sc">$</span>Kappa)</span>
<span id="cb100-14"><a href="#cb100-14" aria-hidden="true" tabindex="-1"></a>smote_test_kappa <span class="ot">=</span> <span class="fu">confusionMatrix</span>(smote_test_class,</span>
<span id="cb100-15"><a href="#cb100-15" aria-hidden="true" tabindex="-1"></a>                                   test<span class="sc">$</span>respondedMailing,</span>
<span id="cb100-16"><a href="#cb100-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">positive =</span> <span class="st">"1"</span>,)<span class="sc">$</span>overall[[<span class="st">"Kappa"</span>]]</span>
<span id="cb100-17"><a href="#cb100-17" aria-hidden="true" tabindex="-1"></a>smote_test_auc <span class="ot">=</span> ModelMetrics<span class="sc">::</span><span class="fu">auc</span>(test<span class="sc">$</span>respondedMailing, smote_test_prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="st">"CV Kappa"</span> <span class="ot">=</span> <span class="fu">c</span>(unbalanced_cv_kappa, down_cv_kappa, smote_cv_kappa),</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>       <span class="st">"Test Kappa"</span> <span class="ot">=</span> <span class="fu">c</span>(unbalanced_test_kappa, down_test_kappa, smote_test_kappa),</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>       <span class="st">"Test AUC"</span> <span class="ot">=</span> <span class="fu">c</span>(unbalanced_test_auc, down_test_auc, smote_test_auc),</span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>       <span class="st">"Tree"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Unbalanced"</span>, <span class="st">"Down"</span>, <span class="st">"SMOTE"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="at">var =</span> <span class="st">"Tree"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               CV Kappa   Test Kappa  Test AUC
Unbalanced 6.837495e-05 0.0007768817 0.5557561
Down       9.436004e-02 0.0362754624 0.5844020
SMOTE      2.264053e-01 0.0332979959 0.5677809</code></pre>
</div>
</div>
</section>
</section>
<section id="create-a-roc-plot-with-auc-to-compare-the-two-models-performance-and-explain-to-nvo-what-the-plot-tells-you." class="level4">
<h4 class="anchored" data-anchor-id="create-a-roc-plot-with-auc-to-compare-the-two-models-performance-and-explain-to-nvo-what-the-plot-tells-you.">7. Create a ROC plot (with AUC) to compare the two model’s performance and explain to NVO what the plot tells you.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">pty=</span><span class="st">"s"</span>)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>unbalanced_roc <span class="ot">=</span> <span class="fu">roc</span>(test<span class="sc">$</span>respondedMailing <span class="sc">~</span> unbalanced_test_prob, </span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">plot=</span><span class="cn">TRUE</span>, <span class="at">print.auc=</span><span class="cn">TRUE</span>, </span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">col=</span><span class="st">"green"</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">legacy.axes=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>down_roc <span class="ot">=</span> <span class="fu">roc</span>(test<span class="sc">$</span>respondedMailing <span class="sc">~</span> down_test_prob,</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">plot=</span><span class="cn">TRUE</span>, <span class="at">print.auc=</span><span class="cn">TRUE</span>, <span class="at">print.auc.y=</span><span class="fl">0.4</span>,</span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">legacy.axes=</span><span class="cn">TRUE</span>, <span class="at">add=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1
Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>smote_roc <span class="ot">=</span> <span class="fu">roc</span>(test<span class="sc">$</span>respondedMailing <span class="sc">~</span> smote_test_prob,</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">plot=</span><span class="cn">TRUE</span>, <span class="at">print.auc=</span><span class="cn">TRUE</span>, <span class="at">print.auc.y=</span><span class="fl">0.3</span>,</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">legacy.axes=</span><span class="cn">TRUE</span>, <span class="at">add=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1
Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">"Unbalanced Data"</span>, <span class="st">"Downsampled Data"</span>, <span class="st">"SMOTE Data"</span>),</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"green"</span>, <span class="st">"blue"</span>, <span class="st">"black"</span>), <span class="at">cex =</span> .<span class="dv">55</span>, <span class="at">lwd=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The ROC/AUC chart shows us how good the model is at distinguishing between positive and negative cases. A good ROC curve would hug the upper left corner of the plot, indicating a high TPR and low FPR. The AUC is the area under that curve, so the larger it is the better, with AUC = .5 being equivalent to random choice, and AUC = 1 meaning perfect classification.</p>
<p>The highest AUC from these decision trees was created from the downsampled data, with AUC = .576. This is not much better than random choice. Our AUC for the lasso logisitic regression model was .602, marginally better than the decision tree on downsampled data.</p>
</section>
<section id="pick-the-best-performing-model-and-view-its-precision-recall-chart-and-its-cumulative-gain-chart." class="level4">
<h4 class="anchored" data-anchor-id="pick-the-best-performing-model-and-view-its-precision-recall-chart-and-its-cumulative-gain-chart.">8. Pick the best performing model, and view its precision recall chart and its cumulative gain chart.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>xy <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x,y)</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>xyp <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(xy<span class="sc">$</span>y,probabilities))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cbind(xy$y, probabilities): number of rows of result is not a
multiple of vector length (arg 1)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>xyp<span class="sc">$</span>V1 <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(xyp<span class="sc">$</span>V1)</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pr_curve</span>(xyp, V1, s0) <span class="sc">%&gt;%</span></span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> recall, <span class="at">y =</span> precision)) <span class="sc">+</span></span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>() <span class="sc">+</span></span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span></span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>respondedMailing <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(test<span class="sc">$</span>respondedMailing)</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>down_explain <span class="ot">=</span> DALEX<span class="sc">::</span><span class="fu">explain</span>(<span class="at">model =</span> down_tree,</span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">data =</span> test,</span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>                               <span class="at">y =</span> test<span class="sc">$</span>respondedMailing<span class="sc">==</span><span class="st">"1"</span>,</span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a>                               <span class="at">type=</span><span class="st">'classification'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Preparation of a new explainer is initiated
  -&gt; model label       :  train.formula  (  default  )
  -&gt; data              :  28622  rows  31  cols 
  -&gt; target variable   :  28622  values 
  -&gt; predict function  :  yhat.train  will be used (  default  )
  -&gt; predicted values  :  No value for predict function target column. (  default  )
  -&gt; model_info        :  package caret , ver. 6.0.94 , task classification (  default  ) 
  -&gt; model_info        :  type set to  classification 
  -&gt; model_info        :  Model info detected classification task but 'y' is a logical . Converted to numeric.  (  NOTE  )
  -&gt; predicted values  :  numerical, min =  0 , mean =  0.4893528 , max =  0.72  
  -&gt; residual function :  difference between y and yhat (  default  )
  -&gt; residuals         :  numerical, min =  -0.72 , mean =  0.459917 , max =  1  
  A new explainer has been created!  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>down_perf <span class="ot">=</span> DALEX<span class="sc">::</span><span class="fu">model_performance</span>(down_explain, <span class="at">cutoff =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">=</span> <span class="fu">plot</span>(down_perf, <span class="at">geom =</span> <span class="st">"prc"</span>)</span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">=</span> <span class="fu">plot</span>(down_perf, <span class="at">geom =</span> <span class="st">"gain"</span>)</span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a>p1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="NVO-donor-classification_files/figure-html/unnamed-chunk-52-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="do">##the predict function doesn't work for my logistic regression model</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a><span class="co">#lasso_explain = DALEX::explain(model = model,</span></span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>                              <span class="co"># data = lasso_test[,-1],</span></span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a>                              <span class="co"># y = lasso_test$respondedMailing=="1",</span></span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>                              <span class="co"># type='classification')</span></span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a><span class="co">#lasso_perf = DALEX::model_performance(lasso_explain, cutoff = 0.5)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="use-the-charts-from-parts-6-and-7-to-describe-how-the-model-should-perform-for-nvo-and-what-it-could-mean-if-they-do-a-mailer-campaign-for-50000-people." class="level4">
<h4 class="anchored" data-anchor-id="use-the-charts-from-parts-6-and-7-to-describe-how-the-model-should-perform-for-nvo-and-what-it-could-mean-if-they-do-a-mailer-campaign-for-50000-people.">9. Use the charts from parts 6 and 7 to describe how the model should perform for NVO and what it could mean if they do a mailer campaign for 50,000 people.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(donors_orig<span class="sc">$</span>averageGiftAmount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.34779</code></pre>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(donors_orig<span class="sc">$</span>respondedMailing <span class="sc">==</span> <span class="st">"TRUE"</span>)) <span class="sc">/</span> <span class="fu">length</span>(donors_orig<span class="sc">$</span>respondedMailing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05075881</code></pre>
</div>
</div>
<p>Say the average mailer costs $1 per mailer. The mean of all donors’ average gift amount is $13.35. With the original response rate of 5.076%, for a 50,000 person campaign, we would spend $50,000 and receive 13.35*50000*.05076 = $33,882 in donations.</p>
<p>If we performed a campaign guided by our lasso logistic regression model, our response rate would be true positive / all predicted positives = 212/(2115+212) = 9.11%. Our $50,000 mailer campaign would now generate 13.35*50000*.0911 = $60809 in donations, resulting in a $10809 profit. The caveat with this model is that, out of 28,622 donors, we only sent mail to 2327 of them, or 8.13%. So, to perform a 50,000 donor campaign, we would need a list of about 615,000 donors. If we don’t have this many potential donors, we could either buy a new list from a data brokerage, or we could lower our positive prediction threshold, but this would lower our precision and ultimately the profit generated from our campaign. I would recommend to NVO to do a smaller mailer campaign, or look into ways to either generate higher donations or decrease the cost of each mailer.</p>
<p>The cumulative gains chart shows a 1:1 relationship between positive rate and true positive rate, so we can comfortably scale our mailer campaign without any precision loss.</p>
<p>The precision recall chart is nearly a horizontal line, meaning that we don’t get any precision loss from increasing recall/sensitivity.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>